import type { Testimonial, ClientPhoto, HeroSlide } from '@/types'

export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Carlos Mendonça',
    car: 'Honda CB 600F Hornet',
    rating: 5,
    text: 'Fui lá sem saber muito sobre financiamento e saí com a minha moto no mesmo dia. Atendimento incrível, sem enrolação nenhuma. Super recomendo!',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80&auto=format',
  },
  {
    id: '2',
    name: 'Mariana Sousa',
    car: 'Yamaha NMAX 160',
    rating: 5,
    text: 'Aprovaram meu financiamento sem entrada e eu nem acreditei! Em menos de uma hora já estava com minha moto. Shopping das Motos é diferente mesmo.',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&q=80&auto=format',
  },
  {
    id: '3',
    name: 'Diego Ferreira',
    car: 'Honda CG 160 Titan',
    rating: 5,
    text: 'Comprei uma moto seminova e tive toda a segurança do mundo. Fizeram vistoria, explicaram tudo e o preço foi justo. Atendimento de primeira!',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=100&q=80&auto=format',
  },
  {
    id: '4',
    name: 'Fernanda Lima',
    car: 'Yamaha Fazer 250',
    rating: 5,
    text: 'Fiz o repasse da minha moto antiga e comprei uma nova. Avaliação justa, rápida e sem burocracia. Deu tudo certo e ainda saí no lucro!',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80&auto=format',
  },
  {
    id: '5',
    name: 'Rodrigo Alves',
    car: 'Honda Biz 125',
    rating: 5,
    text: 'Precisava de uma moto pra trabalhar e não tinha dinheiro pra entrada. O Shopping das Motos aprovou na hora. Salvou minha vida!',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80&auto=format',
  },
  {
    id: '6',
    name: 'Ana Paula Torres',
    car: 'Honda PCX 150',
    rating: 5,
    text: 'Primeira moto da minha vida e o atendimento foi excelente. Explicaram tudo com paciência, financiamento aprovado e entrega no mesmo dia. Amei!',
    avatar: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=100&q=80&auto=format',
  },
]

export const clientPhotos: ClientPhoto[] = [
  {
    id: '1',
    clientName: '',
    carModel: 'Honda CB 600F Hornet',
    image: '/images/motos/moto-5.png',
    tall: false,
  },
  {
    id: '2',
    clientName: '',
    carModel: 'Yamaha MT-03',
    image: '/images/motos/moto-1.png',
    tall: false,
  },
  {
    id: '3',
    clientName: '',
    carModel: 'Honda CG 160 Titan',
    image: '/images/motos/moto-10.png',
    tall: false,
  },
  {
    id: '4',
    clientName: '',
    carModel: 'Yamaha Fazer 250',
    image: '/images/motos/moto-2.png',
    tall: false,
  },
  {
    id: '5',
    clientName: '',
    carModel: 'Yamaha FZ-25',
    image: '/images/motos/moto-6.png',
    tall: false,
  },
  {
    id: '6',
    clientName: '',
    carModel: 'Honda NX 400',
    image: '/images/motos/moto-4.png',
    tall: false,
  },
]

export const heroSlides: HeroSlide[] = [
  {
    id: '1',
    badge: 'SHOPPING DAS MOTOS',
    badgeVariant: 'red',
    headline: 'A moto dos seus\nsonhos te espera.',
    subline: 'Financiamento sem entrada, aprovação na hora. Boa Vista — RR.',
    cta: 'FALAR AGORA',
    ctaVariant: 'white',
    ctaIcon: 'whatsapp',
    bg: '/images/motos/moto-4.png',
    overlay: 0.72,
  },
  {
    id: '2',
    badge: 'FINANCIAMENTO SEM ENTRADA',
    badgeVariant: 'red',
    headline: 'Saia de moto\nhoje mesmo.',
    subline: 'Aprovação facilitada. Sem burocracia, sem enrolação.',
    cta: 'VER ESTOQUE',
    ctaVariant: 'white',
    ctaIcon: 'arrow',
    bg: '/images/motos/moto-2.png',
    overlay: 0.65,
  },
  {
    id: '3',
    badge: 'QUER VENDER SUA MOTO?',
    badgeVariant: 'white',
    headline: 'Fazemos o\nrepasse pra você.',
    subline: 'Avaliação justa e rápida pelo WhatsApp.',
    cta: 'ENVIAR FOTOS',
    ctaVariant: 'red',
    ctaIcon: 'whatsapp',
    bg: '',
    overlay: 0,
  },
]
