import type { Testimonial, ClientPhoto, HeroSlide } from '@/types'

export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Carlos Mendonça',
    car: 'Hilux SRX 2024',
    rating: 5,
    text: 'Rafael me atendeu como se eu fosse da família. Tirou todas as dúvidas, sem pressão. Saí com a Hilux dos meus sonhos dentro do meu orçamento.',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80&auto=format',
  },
  {
    id: '2',
    name: 'Mariana Sousa',
    car: 'Corolla Altis 2023',
    rating: 5,
    text: 'Nunca pensei que comprar um carro seria tão tranquilo. Rafael foi transparente do início ao fim. Recomendo sem hesitar para qualquer pessoa em Roraima.',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&q=80&auto=format',
  },
  {
    id: '3',
    name: 'Diego Ferreira',
    car: 'SW4 Diamond 2024',
    rating: 5,
    text: 'Atendimento impecável e entrega antes do prazo. O Rafael conhece cada detalhe do carro. Profissionalismo de outro nível.',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=100&q=80&auto=format',
  },
  {
    id: '4',
    name: 'Fernanda Lima',
    car: 'RAV4 Hybrid 2022',
    rating: 5,
    text: 'Comprei um seminovo e fiquei com medo de problemas. Rafael me explicou tudo, fez toda a vistoria e eu saí com total segurança. Carro perfeito!',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80&auto=format',
  },
  {
    id: '5',
    name: 'Rodrigo Alves',
    car: 'Hilux 2023',
    rating: 5,
    text: 'Fiz o repasse do meu carro com o Rafael. Avaliação justa, rápida e sem enrolação. Em menos de uma semana já estava com o valor na conta.',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80&auto=format',
  },
  {
    id: '6',
    name: 'Ana Paula Torres',
    car: 'Yaris XLS 2023',
    rating: 5,
    text: 'Primeira compra de carro na vida e o Rafael me deu toda a segurança que precisava. Explicou o financiamento, as parcelas, tudo. Saí satisfeita demais!',
    avatar: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=100&q=80&auto=format',
  },
]

export const clientPhotos: ClientPhoto[] = [
  {
    id: '1',
    clientName: '',
    carModel: 'Toyota Corolla GR Sport 2025',
    image: '/images/carros/corolla.png',
    tall: false,
  },
  {
    id: '2',
    clientName: '',
    carModel: 'Hyundai Creta 2025',
    image: '/images/carros/creta.png',
    tall: false,
  },
  {
    id: '3',
    clientName: '',
    carModel: 'Toyota SW4 2025',
    image: '/images/carros/sw4.png',
    tall: false,
  },
  {
    id: '4',
    clientName: '',
    carModel: 'Toyota SW4 — lateral',
    image: '/images/carros/swadelado.png',
    tall: false,
  },
  {
    id: '5',
    clientName: '',
    carModel: 'Chevrolet S10 2025',
    image: '/images/carros/s10.png',
    tall: false,
  },
  {
    id: '6',
    clientName: '',
    carModel: 'Toyota Yaris GR 2025',
    image: '/images/carros/yaris.png',
    tall: false,
  },
  {
    id: '7',
    clientName: '',
    carModel: 'Toyota Yaris GR — lateral',
    image: '/images/carros/yarisgrdelado.png',
    tall: false,
  },
  {
    id: '8',
    clientName: '',
    carModel: 'Ford Ranger Raptor 2025',
    image: '/images/carros/ranger.png',
    tall: false,
  },
  {
    id: '9',
    clientName: '',
    carModel: 'Chevrolet Onix Plus 2025',
    image: '/images/carros/onixplus.png',
    tall: false,
  },
]

export const heroSlides: HeroSlide[] = [
  {
    id: '1',
    badge: 'SEU CONSULTOR TOYOTA',
    badgeVariant: 'red',
    headline: 'O carro certo,\nna hora certa.',
    subline: 'Mais de 15 anos vendendo confiança em Roraima.',
    cta: 'FALAR AGORA',
    ctaVariant: 'white',
    ctaIcon: 'whatsapp',
    bg: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=1920&q=80&auto=format',
    overlay: 0.72,
  },
  {
    id: '2',
    badge: 'DESTAQUE DO MÊS',
    badgeVariant: 'red',
    headline: 'SW4\nDIAMOND.',
    subline: '2024 • 0km • Híbrido • R$ 489.990',
    cta: 'VER DETALHES',
    ctaVariant: 'white',
    ctaIcon: 'arrow',
    bg: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=1920&q=80&auto=format',
    overlay: 0.65,
  },
  {
    id: '3',
    badge: 'QUER VENDER SEU CARRO?',
    badgeVariant: 'white',
    headline: 'Eu repasso\npara você.',
    subline: 'Avaliação justa e rápida pelo WhatsApp.',
    cta: 'ENVIAR FOTOS',
    ctaVariant: 'red',
    ctaIcon: 'whatsapp',
    bg: '',
    overlay: 0,
  },
]
