import type { Car, Testimonial, ClientPhoto, HeroSlide } from '@/types'

export const cars: Car[] = [
  // ─── NOVOS ────────────────────────────────────────────────────────
  {
    id: '1',
    slug: 'hilux-srx-2024',
    category: 'novo',
    status: 'disponivel',
    brand: 'Toyota',
    model: 'Hilux',
    version: 'SRX',
    year: 2024,
    modelYear: 2024,
    km: 0,
    fuel: 'Diesel',
    transmission: 'Automático',
    color: 'Branco Pérola',
    doors: 4,
    price: 389990,
    negotiable: false,
    shortDescription: 'A rainha das picapes. Tração 4x4, diesel 2.8 turbo e acabamento SRX de primeira linha.',
    description: 'A Toyota Hilux SRX 2024 representa o pico da engenharia japonesa para o segmento de picapes. Com motor diesel 2.8 GD-6 de 204cv e câmbio automático de 6 marchas, ela combina força bruta com refinamento. A tração 4x4 com bloqueio de diferencial garante passagem em qualquer terreno, enquanto o interior premium SRX oferece couro, multimídia de 8" com Apple CarPlay e Android Auto, bancos dianteiros com ventilação e ajuste elétrico. Uma picape que serve tanto para o trabalho pesado quanto para o dia a dia executivo.',
    features: [
      'Tração 4x4 com bloqueio de diferencial',
      'Motor Diesel 2.8 GD-6 204cv',
      'Câmbio automático 6 marchas',
      'Bancos em couro com ventilação',
      'Ajuste elétrico 8 vias do motorista',
      'Multimídia 8" Apple CarPlay/Android Auto',
      'Câmera de ré + sensor de estacionamento',
      'Controle de descida em rampa',
      'Toyota Safety Sense',
      'Faróis Full LED',
      'Rodas de liga 18"',
      'Capota marítima retrátil',
      'Engate para reboque',
      'Controle de cruzeiro adaptativo',
      'Airbags frontais e laterais',
    ],
    highlights: ['4x4 com bloqueio', 'Diesel 204cv', 'SRX Premium'],
    images: [
      'https://images.unsplash.com/photo-1609137144813-7d9921338f24?w=1200&q=80&auto=format',
      'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=1200&q=80&auto=format',
      'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=1200&q=80&auto=format',
      'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=1200&q=80&auto=format',
    ],
    coverImage: 'https://images.unsplash.com/photo-1609137144813-7d9921338f24?w=800&q=80&auto=format',
    featured: true,
    views: 1240,
    createdAt: '2024-01-15',
    metaTitle: 'Toyota Hilux SRX 2024 0km | Rafael Mota - Toyolex Roraima',
    metaDescription: 'Toyota Hilux SRX 2024 0km disponível em Roraima. Motor Diesel 2.8, tração 4x4, câmbio automático. Fale com Rafael Mota, seu consultor Toyota.',
  },
  {
    id: '2',
    slug: 'sw4-diamond-2024',
    category: 'novo',
    status: 'disponivel',
    brand: 'Toyota',
    model: 'SW4',
    version: 'Diamond',
    year: 2024,
    modelYear: 2024,
    km: 0,
    fuel: 'Híbrido',
    transmission: 'Automático',
    color: 'Cinza Granito',
    doors: 4,
    price: 489990,
    negotiable: false,
    shortDescription: 'O SUV mais imponente da Toyota. 7 lugares, motor híbrido e acabamento Diamond exclusivo.',
    description: 'O Toyota SW4 Diamond 2024 é a expressão máxima do luxo e performance no segmento de SUVs. Com sistema de tração híbrida que combina motor elétrico e combustão, entrega potência e eficiência sem precedentes. Os 7 lugares em couro genuíno, o teto panorâmico solar e a multimídia de 9" com JBL premium transformam cada viagem em uma experiência única. O Toyota Safety Sense de segunda geração, com freio autônomo, reconhecimento de pedestres e alerta de faixa, garante máxima segurança para toda a família.',
    features: [
      'Sistema Híbrido elétrico',
      '7 Lugares em couro genuíno',
      'Teto panorâmico solar',
      'Som JBL Premium 11 alto-falantes',
      'Multimídia 9" com navegação',
      'Toyota Safety Sense 2ª geração',
      'Câmera 360°',
      'Rodas de liga 20"',
      'Suspensão pneumática traseira',
      'Faróis Bi-LED adaptativos',
      'Porta-malas elétrico hands-free',
      'Carregamento wireless Qi',
      'Head-up display',
      'Bancos traseiros reclináveis',
      'Controle de cruzeiro radar',
    ],
    highlights: ['7 Lugares Couro', 'Motor Híbrido', 'Diamond Exclusivo'],
    images: [
      'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=1200&q=80&auto=format',
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&q=80&auto=format',
      'https://images.unsplash.com/photo-1606611013016-969c19ba27bb?w=1200&q=80&auto=format',
      'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=1200&q=80&auto=format',
    ],
    coverImage: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80&auto=format',
    featured: true,
    views: 2380,
    createdAt: '2024-01-10',
    metaTitle: 'Toyota SW4 Diamond 2024 0km | Rafael Mota - Toyolex Roraima',
    metaDescription: 'Toyota SW4 Diamond 2024 0km. 7 lugares, sistema híbrido, acabamento Diamond. O SUV mais completo da Toyota em Roraima.',
  },
  {
    id: '3',
    slug: 'corolla-xei-2024',
    category: 'novo',
    status: 'disponivel',
    brand: 'Toyota',
    model: 'Corolla',
    version: 'XEi',
    year: 2024,
    modelYear: 2024,
    km: 0,
    fuel: 'Flex',
    transmission: 'CVT',
    color: 'Prata Metálico',
    doors: 4,
    price: 179990,
    negotiable: false,
    shortDescription: 'O sedã mais vendido do Brasil em sua versão mais equipada. Motor flex 2.0 com CVT.',
    description: 'O Toyota Corolla XEi 2024 é o representante máximo do sedã executivo brasileiro. Motor 2.0 Dynamic Force Flex de 177cv associado ao câmbio CVT de última geração proporciona condução suave e eficiente. O interior da versão XEi conta com revestimento de couro, painel de instrumentos digital de 7", central multimídia de 8" com Apple CarPlay e Android Auto wireless, além do Toyota Safety Sense com freio autônomo, reconhecimento de pedestres e assistente de faixa.',
    features: [
      'Motor 2.0 Dynamic Force Flex 177cv',
      'Câmbio CVT 10 posições simuladas',
      'Painel de instrumentos digital 7"',
      'Central multimídia 8" wireless CarPlay',
      'Revestimento de couro',
      'Toyota Safety Sense',
      'Freio autônomo de emergência',
      'Assistente de manutenção de faixa',
      'Câmera de ré HD',
      'Sensores dianteiros e traseiros',
      'Faróis LED automáticos',
      'Rodas de liga 17"',
      'Controle de cruzeiro adaptativo',
      'Bancos com ajuste elétrico 8 vias',
      'Banco traseiro com apoio de cabeça central',
    ],
    highlights: ['177cv Flex', 'CVT Última Geração', 'Safety Sense'],
    images: [
      'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=1200&q=80&auto=format',
      'https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=1200&q=80&auto=format',
      'https://images.unsplash.com/photo-1541443131876-2ed820890071?w=1200&q=80&auto=format',
      'https://images.unsplash.com/photo-1502877338535-766e1452684a?w=1200&q=80&auto=format',
    ],
    coverImage: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80&auto=format',
    featured: false,
    views: 890,
    createdAt: '2024-02-01',
  },
  {
    id: '4',
    slug: 'corolla-cross-xrx-2024',
    category: 'novo',
    status: 'disponivel',
    brand: 'Toyota',
    model: 'Corolla Cross',
    version: 'XRX',
    year: 2024,
    modelYear: 2024,
    km: 0,
    fuel: 'Híbrido',
    transmission: 'CVT',
    color: 'Preto Eclipse',
    doors: 4,
    price: 249990,
    negotiable: false,
    shortDescription: 'SUV compacto com motor híbrido self-charging. A combinação perfeita de espaço e eficiência.',
    description: 'O Toyota Corolla Cross XRX 2024 combina a praticidade de um SUV compacto com a eficiência do sistema híbrido self-charging da Toyota. Não precisa de tomada — o motor elétrico recarrega durante a frenagem regenerativa. Com tração dianteira, o XRX entrega consumo médio impressionante sem abrir mão do desempenho. Interior premium com couro, teto bipartido, câmera 360° e Toyota Safety Sense completo.',
    features: [
      'Sistema híbrido self-charging',
      'Motor 1.8 + elétrico 98cv combinados',
      'Câmbio CVT',
      'Teto bipartido elétrico',
      'Câmera 360°',
      'Multimídia 9" wireless CarPlay',
      'Revestimento de couro',
      'Toyota Safety Sense',
      'Faróis LED adaptativos',
      'Rodas de liga 18"',
      'Porta-malas elétrico',
      'Carregamento wireless Qi',
      'Head-up display',
      'Assistente de estacionamento automático',
      'Sensores de pressão dos pneus',
    ],
    highlights: ['Híbrido Self-Charging', 'Câmera 360°', 'Teto Bipartido'],
    images: [
      'https://images.unsplash.com/photo-1606611013016-969c19ba27bb?w=1200&q=80&auto=format',
      'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=1200&q=80&auto=format',
      'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=1200&q=80&auto=format',
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&q=80&auto=format',
    ],
    coverImage: 'https://images.unsplash.com/photo-1606611013016-969c19ba27bb?w=800&q=80&auto=format',
    featured: true,
    views: 1540,
    createdAt: '2024-01-20',
  },
  {
    id: '5',
    slug: 'yaris-xl-2024',
    category: 'novo',
    status: 'disponivel',
    brand: 'Toyota',
    model: 'Yaris',
    version: 'XL Sedan',
    year: 2024,
    modelYear: 2024,
    km: 0,
    fuel: 'Flex',
    transmission: 'CVT',
    color: 'Branco Pérola',
    doors: 4,
    price: 119990,
    negotiable: false,
    shortDescription: 'Sedan compacto japonês com confiabilidade Toyota e custo de manutenção imbatível.',
    description: 'O Toyota Yaris XL Sedan 2024 é a porta de entrada para a qualidade Toyota. Motor 1.5 VVT-i Flex de 107cv associado ao CVT proporciona consumo excepcional e manutenção acessível. Perfeito para o uso urbano e viagens, com espaço generoso no banco traseiro e porta-malas de 600 litros. Multimídia de 7" com CarPlay, câmera de ré e o renomado índice de confiabilidade Toyota garantem valor de revenda superior.',
    features: [
      'Motor 1.5 VVT-i Flex 107cv',
      'Câmbio CVT',
      'Multimídia 7" Apple CarPlay',
      'Câmera de ré',
      'Controle de estabilidade',
      'Controle de tração',
      '6 airbags',
      'Faróis de projeção',
      'Rodas de liga 15"',
      'Ar condicionado digital',
      'Direção elétrica',
      'Porta-malas 600 litros',
      'Sensor de estacionamento traseiro',
      'Freio ABS com EBD',
      'Assistente de partida em rampa',
    ],
    highlights: ['Motor Flex', 'Manutenção Econômica', 'Garantia Toyota 3 anos'],
    images: [
      'https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=1200&q=80&auto=format',
      'https://images.unsplash.com/photo-1542362567-b07e54358753?w=1200&q=80&auto=format',
      'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=1200&q=80&auto=format',
    ],
    coverImage: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=800&q=80&auto=format',
    featured: false,
    views: 620,
    createdAt: '2024-02-10',
  },

  // ─── SEMINOVOS ────────────────────────────────────────────────────
  {
    id: '6',
    slug: 'hilux-sr-2022',
    category: 'seminovo',
    status: 'disponivel',
    brand: 'Toyota',
    model: 'Hilux',
    version: 'SR',
    year: 2022,
    modelYear: 2023,
    km: 35000,
    fuel: 'Diesel',
    transmission: 'Manual',
    color: 'Branco Polar',
    doors: 4,
    price: 299990,
    oldPrice: 319990,
    negotiable: true,
    shortDescription: 'Hilux SR seminova com baixíssima quilometragem. Revisada na Toyota e com laudo aprovado.',
    description: 'Toyota Hilux SR 2022/2023 em excelente estado de conservação. Apenas 35.000km rodados por único proprietário. Motor diesel 2.8 GD-6 e câmbio manual de 6 marchas. Revisado na concessionária Toyota com laudo de vistoria cautelar aprovado. Inclui engate de reboque, rodas originais e manual. Oportunidade para quem busca uma Hilux com histórico limpo e preço abaixo da tabela FIPE.',
    features: [
      'Motor Diesel 2.8 GD-6',
      'Câmbio manual 6 marchas',
      'Tração 4x4 com redutor',
      'Multimídia 8"',
      'Câmera de ré',
      'Controle de cruzeiro',
      'Ar condicionado duplo',
      'Engate de reboque',
      'Rodas originais 17"',
      'Revisado na concessionária',
      'Laudo de vistoria aprovado',
      'Único dono',
      'IPVA 2024 pago',
      'Sem multas ou restrições',
      'Manual e chave reserva',
    ],
    highlights: ['Único Dono', 'Diesel 4x4', 'IPVA 2024 Pago'],
    images: [
      'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=1200&q=80&auto=format',
      'https://images.unsplash.com/photo-1609137144813-7d9921338f24?w=1200&q=80&auto=format',
      'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=1200&q=80&auto=format',
    ],
    coverImage: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&q=80&auto=format',
    featured: false,
    views: 780,
    createdAt: '2024-03-01',
  },
  {
    id: '7',
    slug: 'corolla-gli-2022',
    category: 'seminovo',
    status: 'reservado',
    brand: 'Toyota',
    model: 'Corolla',
    version: 'GLi',
    year: 2022,
    modelYear: 2022,
    km: 42000,
    fuel: 'Flex',
    transmission: 'CVT',
    color: 'Vermelho Rubi',
    doors: 4,
    price: 139990,
    negotiable: true,
    shortDescription: 'Corolla GLi 2022 na cobiçada cor Vermelho Rubi. Revisado na Toyota com garantia adicional.',
    description: 'Toyota Corolla GLi 2022 na rara cor Vermelho Rubi Metálico. Motor 2.0 Flex com CVT, consumo médio de 13km/l na cidade. Único dono, revisado na concessionária, com todas as revisões documentadas. Inclui garantia de loja de 90 dias no motor e câmbio. IPVA 2024 pago, licenciamento em dia. Veículo reservado — consulte disponibilidade.',
    features: [
      'Motor 2.0 Flex 177cv',
      'Câmbio CVT',
      'Multimídia 8" CarPlay',
      'Câmera de ré',
      'Sensor de estacionamento',
      'Controle de cruzeiro',
      'Faróis de projeção LED',
      'Rodas de liga 16"',
      'Ar condicionado digital',
      'Único dono',
      'Revisado Toyota',
      'Garantia de loja 90 dias',
      'IPVA 2024 pago',
      'Cor exclusiva Vermelho Rubi',
      'Licenciamento em dia',
    ],
    highlights: ['Único Dono', 'Cor Exclusiva', 'Revisado Toyota'],
    images: [
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=1200&q=80&auto=format',
      'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=1200&q=80&auto=format',
      'https://images.unsplash.com/photo-1541443131876-2ed820890071?w=1200&q=80&auto=format',
    ],
    coverImage: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&q=80&auto=format',
    featured: false,
    views: 450,
    createdAt: '2024-03-10',
  },
  {
    id: '8',
    slug: 'etios-xls-2020',
    category: 'seminovo',
    status: 'vendido',
    brand: 'Toyota',
    model: 'Etios',
    version: 'XLS Sedan',
    year: 2020,
    modelYear: 2020,
    km: 68000,
    fuel: 'Flex',
    transmission: 'Automático',
    color: 'Prata Metálico',
    doors: 4,
    price: 79990,
    negotiable: false,
    shortDescription: 'Etios XLS Sedan automatizado. Confiabilidade Toyota com custo de manutenção reduzido.',
    description: 'Toyota Etios XLS Sedan 2020 com câmbio automatizado de 5 marchas. Motor 1.5 Flex de 105cv com consumo econômico. Veículo em ótimo estado de conservação, com histórico completo de revisões. Ideal para quem busca confiabilidade Toyota com custo de manutenção reduzido. Transferência sem débitos.',
    features: [
      'Motor 1.5 Flex 105cv',
      'Câmbio automatizado 5 marchas',
      'Multimídia com Bluetooth',
      'Câmera de ré',
      'Ar condicionado',
      'Direção elétrica',
      'Freio ABS',
      'Airbags frontais',
      'Controle de tração',
      'Rodas de liga 15"',
    ],
    highlights: ['Automatizado', 'Flex Economy', 'Revisões em Dia'],
    images: [
      'https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=1200&q=80&auto=format',
      'https://images.unsplash.com/photo-1542362567-b07e54358753?w=1200&q=80&auto=format',
    ],
    coverImage: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=800&q=80&auto=format',
    featured: false,
    views: 320,
    createdAt: '2024-02-20',
    soldAt: '2024-03-15',
  },
  {
    id: '9',
    slug: 'rav4-hybrid-2021',
    category: 'seminovo',
    status: 'disponivel',
    brand: 'Toyota',
    model: 'RAV4',
    version: 'Hybrid AWD',
    year: 2021,
    modelYear: 2022,
    km: 41000,
    fuel: 'Híbrido',
    transmission: 'CVT',
    color: 'Branco Blizzard',
    doors: 4,
    price: 229990,
    negotiable: true,
    shortDescription: 'RAV4 Hybrid AWD seminovo. Tração integral elétrica, 222cv e consumo de 14km/l.',
    description: 'Toyota RAV4 Hybrid AWD 2021/2022 em excelente estado. Sistema de tração integral elétrica E-Four, sem eixo cardã, com motor dianteiro a combustão e motor traseiro 100% elétrico, totalizando 222cv combinados. Consumo médio de 14km/l na cidade. Teto solar panorâmico, couro beige, multimídia de 9" e câmera 360° completos. Revisado e com laudo de vistoria aprovado. Único dono.',
    features: [
      'Sistema Híbrido E-Four AWD',
      '222cv combinados',
      'Teto solar panorâmico',
      'Couro beige premium',
      'Multimídia 9"',
      'Câmera 360°',
      'Toyota Safety Sense 2.0',
      'Faróis Full LED',
      'Rodas de liga 18"',
      'Porta-malas 580 litros',
      'Único dono',
      'Revisado Toyota',
      'IPVA 2024 pago',
      'Laudo de vistoria aprovado',
      'Consumo 14km/l cidade',
    ],
    highlights: ['AWD Elétrico', '222cv Híbrido', 'Teto Solar'],
    images: [
      'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=1200&q=80&auto=format',
      'https://images.unsplash.com/photo-1606611013016-969c19ba27bb?w=1200&q=80&auto=format',
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&q=80&auto=format',
      'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=1200&q=80&auto=format',
    ],
    coverImage: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&q=80&auto=format',
    featured: true,
    views: 1120,
    createdAt: '2024-02-15',
  },
  {
    id: '10',
    slug: 'sw4-srx-2021',
    category: 'seminovo',
    status: 'disponivel',
    brand: 'Toyota',
    model: 'SW4',
    version: 'SRX',
    year: 2021,
    modelYear: 2022,
    km: 55000,
    fuel: 'Diesel',
    transmission: 'Automático',
    color: 'Cinza Granito',
    doors: 4,
    price: 339990,
    negotiable: true,
    shortDescription: 'SW4 SRX 7 lugares diesel. O SUV mais robusto da Toyota em excelente estado de conservação.',
    description: 'Toyota SW4 SRX 2021/2022 diesel com 7 lugares. Motor GD-6 2.8 turbodiesel de 204cv e câmbio automático de 6 marchas. Tração 4x4 permanente com redução. Interior SRX com couro preto, teto solar panorâmico, som JBL e multimídia de 9". Revisado na concessionária Toyota com todas as revisões documentadas. Segundo dono em ótimo estado geral.',
    features: [
      'Motor Diesel 2.8 GD-6 204cv',
      'Câmbio automático 6 marchas',
      '7 Lugares couro preto',
      'Tração 4x4 com redutor',
      'Teto solar panorâmico',
      'Som JBL premium',
      'Multimídia 9"',
      'Toyota Safety Sense',
      'Câmera 360°',
      'Faróis Full LED',
      'Rodas de liga 20"',
      'Revisado Toyota',
      'IPVA 2024 pago',
      'Laudo aprovado',
      '2º dono, histórico limpo',
    ],
    highlights: ['7 Lugares Diesel', 'SRX Premium', 'Revisado Toyota'],
    images: [
      'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=1200&q=80&auto=format',
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&q=80&auto=format',
      'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=1200&q=80&auto=format',
    ],
    coverImage: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80&auto=format',
    featured: true,
    views: 1850,
    createdAt: '2024-01-25',
  },

  // ─── REPASSE ──────────────────────────────────────────────────────
  {
    id: '11',
    slug: 'civic-touring-2022',
    category: 'repasse',
    status: 'vendido',
    brand: 'Honda',
    model: 'Civic',
    version: 'Touring',
    year: 2022,
    modelYear: 2022,
    km: 38000,
    fuel: 'Gasolina',
    transmission: 'CVT',
    color: 'Preto Cristal',
    doors: 4,
    price: 149990,
    negotiable: false,
    shortDescription: 'Civic Touring 2022 top de linha. Motor turbo 1.5, 174cv, CVT e Honda Sensing completo.',
    description: 'Honda Civic Touring 2022 top de linha com motor 1.5 VTEC Turbo de 174cv. Honda Sensing completo com CMBS, ACC, Lane Watch e LKA. Interior com couro, teto solar, multimídia de 9" com wireless CarPlay e painel digital de 10.2". Único dono, revisado Honda, todos os itens originais.',
    features: [
      'Motor 1.5 VTEC Turbo 174cv',
      'Câmbio CVT',
      'Honda Sensing completo',
      'Teto solar',
      'Couro',
      'Painel digital 10.2"',
      'Multimídia 9"',
      'Câmera traseira HD',
      'Rodas de liga 17"',
    ],
    highlights: ['Turbo 174cv', 'Honda Sensing', 'Único Dono'],
    images: [
      'https://images.unsplash.com/photo-1542362567-b07e54358753?w=1200&q=80&auto=format',
      'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=1200&q=80&auto=format',
    ],
    coverImage: 'https://images.unsplash.com/photo-1542362567-b07e54358753?w=800&q=80&auto=format',
    featured: false,
    views: 290,
    createdAt: '2024-02-01',
    soldAt: '2024-04-02',
  },
  {
    id: '12',
    slug: 'compass-limited-2023',
    category: 'repasse',
    status: 'disponivel',
    brand: 'Jeep',
    model: 'Compass',
    version: 'Limited',
    year: 2023,
    modelYear: 2023,
    km: 28000,
    fuel: 'Flex',
    transmission: 'Automático',
    color: 'Branco Polar',
    doors: 4,
    price: 169990,
    negotiable: true,
    shortDescription: 'Jeep Compass Limited 2023 impecável. Apenas 28.000km, couro, teto solar e câmera 360°.',
    description: 'Jeep Compass Limited 2023 em estado impecável com apenas 28.000km. Motor T270 1.3 turbo flex de 185cv com câmbio automático de 9 marchas. Interior Limited com couro, teto solar de 3 estágios, multimídia Uconnect de 10.1" com wireless CarPlay, câmera 360° e faróis Full LED. Único dono, revisado na concessionária Jeep.',
    features: [
      'Motor 1.3 Turbo Flex 185cv',
      'Câmbio automático 9 marchas',
      'Teto solar 3 estágios',
      'Couro premium',
      'Multimídia Uconnect 10.1"',
      'Wireless Apple CarPlay',
      'Câmera 360°',
      'Faróis Full LED',
      'Rodas de liga 19"',
      'Freio autônomo de emergência',
      'Detector de ponto cego',
      'Único dono',
      'Revisado Jeep',
      'IPVA 2024 pago',
      'Sem restrições',
    ],
    highlights: ['Baixa KM', 'Teto Solar', 'Full LED'],
    images: [
      'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=1200&q=80&auto=format',
      'https://images.unsplash.com/photo-1606611013016-969c19ba27bb?w=1200&q=80&auto=format',
      'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=1200&q=80&auto=format',
    ],
    coverImage: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&q=80&auto=format',
    featured: false,
    views: 670,
    createdAt: '2024-03-05',
  },
  {
    id: '13',
    slug: 'hb20-comfort-2023',
    category: 'repasse',
    status: 'vendido',
    brand: 'Hyundai',
    model: 'HB20',
    version: 'Comfort Plus',
    year: 2023,
    modelYear: 2023,
    km: 22000,
    fuel: 'Flex',
    transmission: 'Automático',
    color: 'Azul Intense',
    doors: 4,
    price: 89990,
    negotiable: false,
    shortDescription: 'HB20 Comfort Plus 2023 quase novo. Apenas 22.000km, automático e Apple CarPlay.',
    description: 'Hyundai HB20 Comfort Plus 2023 na cor Azul Intense com apenas 22.000km. Motor 1.0 turbo de 120cv com câmbio automático de 6 marchas. Multimídia de 8" com Apple CarPlay e Android Auto, câmera de ré e controle de estabilidade. Veículo praticamente novo, revisado e com IPVA pago.',
    features: [
      'Motor 1.0 Turbo 120cv',
      'Câmbio automático 6 marchas',
      'Multimídia 8" CarPlay',
      'Câmera de ré',
      'Controle de estabilidade',
      'Controle de tração',
      '6 airbags',
      'Rodas de liga 15"',
      'Ar condicionado digital',
    ],
    highlights: ['Quase Novo', 'Turbo Flex', '22.000km'],
    images: [
      'https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=1200&q=80&auto=format',
      'https://images.unsplash.com/photo-1502877338535-766e1452684a?w=1200&q=80&auto=format',
    ],
    coverImage: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=800&q=80&auto=format',
    featured: false,
    views: 180,
    createdAt: '2024-03-15',
    soldAt: '2024-04-20',
  },
  {
    id: '14',
    slug: 'nivus-highline-2022',
    category: 'repasse',
    status: 'disponivel',
    brand: 'Volkswagen',
    model: 'Nivus',
    version: 'Highline',
    year: 2022,
    modelYear: 2022,
    km: 45000,
    fuel: 'Flex',
    transmission: 'Automático',
    color: 'Preto Ninja',
    doors: 4,
    price: 109990,
    oldPrice: 119990,
    negotiable: true,
    shortDescription: 'VW Nivus Highline na cor Preto Ninja. Motor TSI turbo, teto solar e IQ.Drive completo.',
    description: 'Volkswagen Nivus Highline 2022 na cobiçada cor Preto Ninja Perolizado. Motor 1.0 TSI de 116cv com câmbio automático de 6 marchas e teto solar. Pacote IQ.Drive completo: frenagem autônoma, reconhecimento de fadiga, detector de ponto cego, controle de cruzeiro adaptativo e assistente de manutenção de faixa. Multimídia Discover Pro de 10" com wireless CarPlay. Único dono, revisado VW.',
    features: [
      'Motor 1.0 TSI 116cv',
      'Câmbio automático 6 marchas',
      'Teto solar',
      'IQ.Drive completo',
      'Frenagem autônoma',
      'Detector de ponto cego',
      'Multimídia Discover Pro 10"',
      'Wireless Apple CarPlay',
      'Câmera traseira',
      'Faróis LED',
      'Rodas de liga 17"',
      'Único dono',
      'Revisado VW',
      'IPVA 2024 pago',
      'Cor Preto Ninja Perolizado',
    ],
    highlights: ['TSI Turbo', 'Teto Solar', 'IQ.Drive Completo'],
    images: [
      'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=1200&q=80&auto=format',
      'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=1200&q=80&auto=format',
      'https://images.unsplash.com/photo-1541443131876-2ed820890071?w=1200&q=80&auto=format',
    ],
    coverImage: 'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800&q=80&auto=format',
    featured: false,
    views: 530,
    createdAt: '2024-03-20',
  },
  {
    id: '15',
    slug: 'tracker-premier-2022',
    category: 'repasse',
    status: 'reservado',
    brand: 'Chevrolet',
    model: 'Tracker',
    version: 'Premier',
    year: 2022,
    modelYear: 2022,
    km: 51000,
    fuel: 'Flex',
    transmission: 'Automático',
    color: 'Branco Summit',
    doors: 4,
    price: 119990,
    negotiable: false,
    shortDescription: 'Chevrolet Tracker Premier top de linha. Motor turbo, couro, teto panorâmico e MyLink 8".',
    description: 'Chevrolet Tracker Premier 2022 na top de linha. Motor 1.2 Turbo Flex de 133cv com câmbio automático de 6 marchas. Teto panorâmico elétrico, couro, multimídia MyLink de 8" com Apple CarPlay sem fio, câmera 360° e pacote de segurança completo com frenagem autônoma. Único dono, revisado na Chevrolet, com todas as revisões documentadas.',
    features: [
      'Motor 1.2 Turbo Flex 133cv',
      'Câmbio automático 6 marchas',
      'Teto panorâmico elétrico',
      'Couro premium',
      'Multimídia MyLink 8"',
      'Wireless Apple CarPlay',
      'Câmera 360°',
      'Frenagem autônoma',
      'Detector de ponto cego',
      'Faróis Full LED',
      'Rodas de liga 17"',
      'Único dono',
      'Revisado Chevrolet',
      'IPVA 2024 pago',
    ],
    highlights: ['Teto Panorâmico', 'Premier Top', 'Único Dono'],
    images: [
      'https://images.unsplash.com/photo-1606611013016-969c19ba27bb?w=1200&q=80&auto=format',
      'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=1200&q=80&auto=format',
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&q=80&auto=format',
    ],
    coverImage: 'https://images.unsplash.com/photo-1606611013016-969c19ba27bb?w=800&q=80&auto=format',
    featured: false,
    views: 390,
    createdAt: '2024-03-25',
  },
]

export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Carlos Mendonça',
    car: 'Hilux SRX 2024',
    rating: 5,
    text: 'Rafael me atendeu como se eu fosse da família. Tirou todas as dúvidas, sem pressão. Saí com a Hilux dos meus sonhos dentro do meu orçamento.',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80&auto=format',
  },
  {
    id: '2',
    name: 'Mariana Sousa',
    car: 'Corolla Altis 2023',
    rating: 5,
    text: 'Nunca pensei que comprar um carro seria tão tranquilo. Rafael foi transparente do início ao fim. Recomendo sem hesitar para qualquer pessoa em Roraima.',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&q=80&auto=format',
  },
  {
    id: '3',
    name: 'Diego Ferreira',
    car: 'SW4 Diamond 2024',
    rating: 5,
    text: 'Atendimento impecável e entrega antes do prazo. O Rafael conhece cada detalhe do carro. Profissionalismo de outro nível.',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=100&q=80&auto=format',
  },
  {
    id: '4',
    name: 'Fernanda Lima',
    car: 'RAV4 Hybrid 2022',
    rating: 5,
    text: 'Comprei um seminovo e fiquei com medo de problemas. Rafael me explicou tudo, fez toda a vistoria e eu saí com total segurança. Carro perfeito!',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80&auto=format',
  },
  {
    id: '5',
    name: 'Rodrigo Alves',
    car: 'Hilux 2023',
    rating: 5,
    text: 'Fiz o repasse do meu carro com o Rafael. Avaliação justa, rápida e sem enrolação. Em menos de uma semana já estava com o valor na conta.',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80&auto=format',
  },
  {
    id: '6',
    name: 'Ana Paula Torres',
    car: 'Yaris XLS 2023',
    rating: 5,
    text: 'Primeira compra de carro na vida e o Rafael me deu toda a segurança que precisava. Explicou o financiamento, as parcelas, tudo. Saí satisfeita demais!',
    avatar: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=100&q=80&auto=format',
  },
]

export const clientPhotos: ClientPhoto[] = [
  {
    id: '1',
    clientName: 'Carlos e família',
    carModel: 'Hilux SRX 2024',
    image: 'https://images.unsplash.com/photo-1609137144813-7d9921338f24?w=600&q=80&auto=format',
    tall: false,
  },
  {
    id: '2',
    clientName: 'Mariana S.',
    carModel: 'Corolla XEi 2024',
    image: 'https://images.unsplash.com/photo-1546614042-7df3c24c9e5d?w=600&q=80&auto=format',
    tall: true,
  },
  {
    id: '3',
    clientName: 'Diego F.',
    carModel: 'SW4 Diamond 2024',
    image: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=600&q=80&auto=format',
    tall: false,
  },
  {
    id: '4',
    clientName: 'Família Ferreira',
    carModel: 'RAV4 Hybrid 2021',
    image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=600&q=80&auto=format',
    tall: true,
  },
  {
    id: '5',
    clientName: 'Rodrigo A.',
    carModel: 'Hilux SR 2022',
    image: 'https://images.unsplash.com/photo-1541443131876-2ed820890071?w=600&q=80&auto=format',
    tall: false,
  },
  {
    id: '6',
    clientName: 'Ana Paula T.',
    carModel: 'Yaris XL 2024',
    image: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=600&q=80&auto=format',
    tall: false,
  },
  {
    id: '7',
    clientName: 'Marcos e esposa',
    carModel: 'Corolla Cross XRX 2024',
    image: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=600&q=80&auto=format',
    tall: true,
  },
  {
    id: '8',
    clientName: 'Juliana M.',
    carModel: 'SW4 SRX 2021',
    image: 'https://images.unsplash.com/photo-1502877338535-766e1452684a?w=600&q=80&auto=format',
    tall: false,
  },
  {
    id: '9',
    clientName: 'Família Souza',
    carModel: 'Compass Limited 2023',
    image: 'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=600&q=80&auto=format',
    tall: false,
  },
]

export const heroSlides: HeroSlide[] = [
  {
    id: '1',
    badge: 'SEU CONSULTOR TOYOTA',
    badgeVariant: 'red',
    headline: 'O carro certo,\nna hora certa.',
    subline: 'Mais de 15 anos vendendo confiança em Roraima.',
    cta: 'FALAR AGORA',
    ctaVariant: 'white',
    ctaIcon: 'whatsapp',
    bg: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=1920&q=80&auto=format',
    overlay: 0.72,
  },
  {
    id: '2',
    badge: 'DESTAQUE DO MÊS',
    badgeVariant: 'red',
    headline: 'SW4\nDIAMOND.',
    subline: '2024 • 0km • Híbrido • R$ 489.990',
    cta: 'VER DETALHES',
    ctaVariant: 'white',
    ctaIcon: 'arrow',
    bg: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=1920&q=80&auto=format',
    overlay: 0.65,
  },
  {
    id: '3',
    badge: 'QUER VENDER SEU CARRO?',
    badgeVariant: 'white',
    headline: 'Eu repasso\npara você.',
    subline: 'Avaliação justa e rápida pelo WhatsApp.',
    cta: 'ENVIAR FOTOS',
    ctaVariant: 'red',
    ctaIcon: 'whatsapp',
    bg: '',
    overlay: 0,
  },
]
